version: '3.7'
networks:
  ad-hoc-network:
    name: network-where-rabbitmq-lives
services:
  rabbitmq:
    image: rabbitmq:management
    networks:
      - ad-hoc-network
    ports:
      - "5672:5672"
      - "15672:15672"
  restonode-api:
    build: .
    networks:
      - ad-hoc-network
    ports:
      - "8080:8080"
    environment:
      - DISTANCE_MATRIX_API_KEY=AIzaSyCpdWlCVR_vz2LiH42OSJnMEIhDjntdeoA
      - RABBIT_HOST=rabbitmq

#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8888:8080"