version: '3.7'

networks:
  ad-hoc-network:
    name: backend-network

services:

  rabbitmq:
    image: rabbitmq:management
    networks:
      - ad-hoc-network
    ports:
      - "5672:5672"
      - "15672:15672"

  restonode-api:
    build: .
    networks:
      - ad-hoc-network
    ports:
      - "8080:8080"
    environment:
      - DISTANCE_MATRIX_API_KEY=WATCH OUT!-REPLACE THIS WITH PROVIDED API KEY!
      - RABBIT_HOST=rabbitmq
