logging:
  level:
    org.springframework.web: INFO
    com.truenorth.restonode: DEBUG

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    exchange:
      name: restonode_topic_exchange
    routingKey:
      notification: restonode_routingKey_notification
      order: restonode_routingKey_order

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true